from __future__ import annotations

import json
from textwrap import dedent

from .charting import ChartSpec


def generate_reproducible_code(spec: ChartSpec, data_path: str | None = None) -> str:
    path_expr = repr(data_path) if data_path else "'your_data.csv'"
    spec_json = json.dumps(spec.to_dict(), ensure_ascii=False, indent=2)
    return dedent(
        f"""
# Reproducible plotting code generated by SciFigure AI Studio
import json
import pandas as pd
from scifigure.charting import ChartEngine, ChartSpec

DATA_PATH = {path_expr}
spec = ChartSpec(**json.loads(r'''{spec_json}'''))

if DATA_PATH.endswith(('.xlsx', '.xls')):
    df = pd.read_excel(DATA_PATH)
elif DATA_PATH.endswith('.parquet'):
    df = pd.read_parquet(DATA_PATH)
elif DATA_PATH.endswith('.json'):
    df = pd.read_json(DATA_PATH)
else:
    df = pd.read_csv(DATA_PATH)

engine = ChartEngine()
fig = engine.render(df, spec)
fig.savefig('figure.png', dpi=600, bbox_inches='tight')
fig.savefig('figure.svg', bbox_inches='tight')
print('Saved figure.png and figure.svg')
"""
    ).strip()
