from __future__ import annotations

import json
from textwrap import dedent

from .charting import ChartSpec


def generate_reproducible_code(spec: ChartSpec, data_path: str | None = None) -> str:
    path_expr = repr(data_path) if data_path else "'your_data.csv'"
    spec_json = json.dumps(spec.to_dict(), ensure_ascii=False, indent=2)
    return dedent(f'''
    # Reproducible plotting code generated by SciFigure AI Studio
    import json
    import pandas as pd
    import matplotlib.pyplot as plt
    import seaborn as sns
    import numpy as np

    DATA_PATH = {path_expr}
    spec = json.loads(r''' + "'''" + spec_json + "'''" + r''')

    if DATA_PATH.endswith(('.xlsx', '.xls')):
        df = pd.read_excel(DATA_PATH)
    elif DATA_PATH.endswith('.parquet'):
        df = pd.read_parquet(DATA_PATH)
    elif DATA_PATH.endswith('.json'):
        df = pd.read_json(DATA_PATH)
    else:
        df = pd.read_csv(DATA_PATH)

    sns.set_theme(style='whitegrid', context='paper')
    plt.rcParams.update({
        'figure.dpi': spec.get('dpi', 140),
        'savefig.dpi': 600,
        'pdf.fonttype': 42,
        'ps.fonttype': 42,
        'svg.fonttype': 'none',
        'axes.unicode_minus': False,
        'font.sans-serif': ['Microsoft YaHei', 'SimHei', 'Arial Unicode MS', 'DejaVu Sans'],
    })

    fig, ax = plt.subplots(
        figsize=(spec.get('width', 7.2), spec.get('height', 4.8)),
        dpi=spec.get('dpi', 140),
        constrained_layout=True,
    )

    chart_type = spec.get('chart_type', '散点图')
    x, y, y2, hue = spec.get('x'), spec.get('y'), spec.get('y2'), spec.get('hue')

    if spec.get('aggregate') != 'none' and x and y:
        if spec['aggregate'] == 'count':
            df = df.groupby(x, dropna=False).size().reset_index(name=y)
        else:
            df = df.groupby(x, dropna=False, as_index=False)[y].agg(spec['aggregate'])

    if spec.get('sort_x') and x:
        df = df.sort_values(x)

    if chart_type in {'智能识别', 'AI 智能识别'}:
        numeric = list(df.select_dtypes(include=np.number).columns)
        chart_type = '散点图' if len(numeric) >= 2 else ('直方图' if numeric else '热力图')
        if len(numeric) >= 2:
            x, y = numeric[0], numeric[1]
        elif numeric:
            x = numeric[0]

    if chart_type == '散点图':
        sns.scatterplot(data=df, x=x, y=y, hue=hue, ax=ax, s=56, edgecolor='white', linewidth=0.4)
    elif chart_type == '折线图':
        sns.lineplot(data=df, x=x, y=y, hue=hue, marker='o', ax=ax)
    elif chart_type == '柱状图':
        sns.barplot(data=df, x=x, y=y, hue=hue, ax=ax, errorbar='sd')
    elif chart_type == '水平柱状图':
        sns.barplot(data=df, y=x, x=y, hue=hue, ax=ax, errorbar='sd')
    elif chart_type == '直方图':
        sns.histplot(data=df, x=x, hue=hue, kde=True, ax=ax)
    elif chart_type == '箱线图':
        sns.boxplot(data=df, x=x, y=y, hue=hue, ax=ax)
    elif chart_type == '小提琴图':
        sns.violinplot(data=df, x=x, y=y, hue=hue, inner='quartile', ax=ax)
    elif chart_type == '相关矩阵':
        corr = df.select_dtypes(include=np.number).corr()
        sns.heatmap(corr, annot=True, fmt='.2f', cmap='vlag', center=0, square=True, ax=ax)
    elif chart_type == '热力图':
        sns.heatmap(df.select_dtypes(include=np.number), cmap='viridis', ax=ax)
    elif chart_type == '回归图':
        sns.regplot(data=df, x=x, y=y, ax=ax)
        if hue:
            sns.scatterplot(data=df, x=x, y=y, hue=hue, ax=ax, s=42)
    elif chart_type == '误差棒':
        error_col = spec.get('error_col')
        yerr = df[error_col].to_numpy() if error_col else None
        ax.errorbar(df[x], df[y], yerr=yerr, fmt='o-', capsize=4, linewidth=1.8)
    elif chart_type == '双Y轴':
        ax.plot(df[x], df[y], marker='o', label=y)
        ax2 = ax.twinx()
        ax2.plot(df[x], df[y2], marker='s', linestyle='--', label=y2)
        ax2.set_ylabel(y2)
        lines, labels = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines + lines2, labels + labels2, loc='best')
    elif chart_type == '面积图':
        ax.fill_between(df[x], df[y], alpha=0.35)
        ax.plot(df[x], df[y], linewidth=2)
    elif chart_type == '饼图':
        pie_df = df[[x, y]].dropna().sort_values(y, ascending=False).head(12)
        ax.pie(pie_df[y], labels=pie_df[x].astype(str), autopct='%1.1f%%', startangle=90)
        ax.axis('equal')
    elif chart_type == 'KDE 密度图':
        sns.kdeplot(data=df, x=x, hue=hue, fill=True, ax=ax)
    else:
        raise ValueError(f'Unsupported chart type: {chart_type}')

    ax.set_title(spec.get('title') or '')
    ax.set_xlabel(spec.get('xlabel') or (x or ''))
    ax.set_ylabel(spec.get('ylabel') or (y or ''))
    if spec.get('log_x'):
        ax.set_xscale('log')
    if spec.get('log_y'):
        ax.set_yscale('log')
    ax.grid(spec.get('grid', True), alpha=0.25)
    if not spec.get('legend', True) and ax.get_legend():
        ax.get_legend().remove()
    for label in ax.get_xticklabels():
        label.set_rotation(25)
        label.set_horizontalalignment('right')

    fig.savefig('figure.png', dpi=600, bbox_inches='tight')
    fig.savefig('figure.svg', bbox_inches='tight')
    plt.show()
    ''').strip()
